[package]
name = "ripple_extn_xvp"
version = "0.1.0"
edition = "2021"
repository = "https://github.comcast.com/ottx/ripple_extn_xvp"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ripple_sdk = { path = "../ripple_sdk" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16.1", features = ["macros", "sync", "rt", "signal"] }
semver = "*"
async-trait = "^0.1.57"
jsonrpsee = { version = "0.9.0", features = ["macros", "server"]}
