#!/bin/sh

echo "pull all sub modules"
git submodule update --init --recursive

# TODO remove this dependency when we have more platforms
cd Ripple
echo "Building OSS"
cargo build
cd ..
cd ripple_comcast_extns
echo "Building Comcast Extns"
cargo build
cd ..