[registries.partner_artifactory]
index = "sparse+https://partners.artifactory.comcast.com/artifactory/api/cargo/eos-ripple/index/"
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

