@startuml "Cloud Permissions Check"

title "Cloud Permissions Check"
participant handler as "Handler"
participant ripple_helper as "Ripple Helper"
participant dpab as "Distributor Platform"
participant permission_service as "Permissions Service"
participant thor_permission_service as "Cloud Permission Service"
group Ripple  Helper
  handler -> ripple_helper: send_dab()
  ripple_helper -> ripple_helper: send()
  ripple_helper -> dpab : get_distributor_session()
  dpab -> ripple_helper: distributor_session
  ripple_helper -> ripple_helper: get_api_call_grant()
  ripple_helper -> permission_service: get_api_call_grant()
  permission_service -> thor_permission_service : get_thor_token()
  permission_service -> permission_service: firebolt_api_to_tp_api()
  note left of permission_service: firebolt api name must be translated into tp api name. e.g.: `device.model`
  permission_service -> thor_permission_service : authorize()

  thor_permission_service -> permission_service: permissions
  note left of permission_service: example reply: "{'authorization': {'permissions': ['DATA_deviceCapabilities.model']}}"

  note left of permission_service: Check if requested permission is in grant list
  alt requested permission is in allowed list
    permission_service -> ripple_helper: allowed_permissions
  else 
    permission_service -> ripple_helper: permission_denied
  end
    alt allowed_permissions
    ripple_helper -> dab: send
    dab -> ripple_helper: response
    ripple_helper -> handler : response
  else
    ripple_helper -> handler: error_denied
  end


end 

@enduml