@startuml "XVP Extension"
title "XVP Extn"

box "App"  #LightBlue
    participant a as "App"
end box

box "Ripple" #Yellow
    participant m as "Main"
    participant pm as "Plugin\nManager"
    participant rpc as "RPC\nGateway"
end box

box "Xvp Extn" #LightGreen
    participant x as "XVP\nPlugin"
    participant c as "XVP\nChannel"
    participant r as "XVP\nRpc"
end box

group "init phase"
    m -> pm : load plugins
    pm -> pm : initialize helper
    pm -> x : get extensions
    x <-> c : get channel extn
    note right of x: "privacy.getOptOut"
    x <-> r : get rpc extn(helper)
    pm -> m : Loaded Extensions
    m -> rpc : Merge extension rpc's
end

group "call phase"
    a -> r : privacy.getOptOut
    r -> pm: helper.get("ripple:channel:data-governance",optout)
    pm <-> c: get value
    pm -> r: opt_out value
    r -> a : {jsonrpc:"1.0",result:{"value": "opt_out_value"}}
end

